name: twim
favicon: null
layout_spectrum: 0.99007
typography_spectrum: 0.13612
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d303f'
    - '#a6cbec'
    - '#f5f3f6'
    - '#8a9bab'
    - '#e2b4a1'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
