name: twim
favicon: null
layout_spectrum: 0.1025864533148706
typography_spectrum: 0.6392591407056898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.0750829610042274
  lightness: 0.9915928288828582
  saturation: 0.3889915212057531
  rhythmicContrast: 0.05413765902630985
purpose: []
