name: twim
favicon: null
layout_spectrum: 0.83212
typography_spectrum: 0.15699
title: a new way of advise
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#0f61ae'
    - '#0000ff'
    - '#000080'
    - '#004080'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
